## 32位随机数
#roncoo:
#  secret: ${random.value}
#  number: ${random.int}
#  name: www.roncoo.com
#  desc: ${roncoo.name} is a domain name
#
#server:
#  port: 80
#
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Chongqing
#
#---
#spring:
#  profiles:
#    active: dev
#server:
#  port: 8080
#---
#spring:
#  profiles:
#    active: test
#server:
#  port: 8081
#---
#spring:
#  profiles:
#    active: pre
#server:
#  port: 8082
#---